# Define the version of a Docker Compose file.
version: "3.8"

# Define services that will be utilized.
services:
  # Service 1, named "item-app".
  item-app:
    # Use image from docker hub sholihin29 with tag v1
    image: sholihin29/item-app:v1
    # Use port Host 80 and port 8080 for container
    ports:
      - 81:8080
    # Will always restart if the container dies due to server restarts
    restart: always
    # It will wait for "item-db" to start before starting this service
    depends_on:
      - item-db
  # Service 1, named "item-app".
  item-db:
    # Use image with named "mongo" with tag "3" and the mongo version will follow
    image: mongo:3
    # Will always restart if the container dies due to server restarts
    restart: always
    # Define volume of service and and install into /data/db
    volumes:
      - app-db:/data/db
# New volume with name app-db
volumes:
  app-db: