# Define the version of a Docker Compose file.
version: "3.8"

# Define services that will be utilized.
services:
  # Service 1, named "item-app".
  item-app:
    # Use image with named "node" with tag "14.21.3" and the node version will follow
    image: node:14.21.3
    # Install dependencies and build the application and start application
    command: sh -c "npm install --production --unsafe-perm && npm run build && npm start"
    # Use port Host 80 and port 8080 for container
    ports:
      - 80:8080
    # Will always restart if the container dies due to server restarts
    restart: always
    # Use working directory /app
    working_dir: /app
    # Use volume ./:/app
    volumes:
      - ./:/app
    # Setup environtment
    environment:
      NODE_ENV: production 
      DB_HOST: item-db
    # It will wait for "item-db" to start before starting this service
    depends_on:
      - item-db
  # Service 1, named "item-app".
  item-db:
    # Use image with named "mongo" with tag "3" and the mongo version will follow
    image: mongo:3
    # Will always restart if the container dies due to server restarts
    restart: always
    # Define volume of service and and install into /data/db
    volumes:
      - app-db:/data/db
# New volume with name app-db
volumes:
  app-db: